spring.application.name=my-spring-api
server.port=8080
app.env=${APP_ENV:dev}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
