kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    labels:
      node-role.kubernetes.io/control-plane: "true"
  - role: worker
    labels:
      custom-name: worker-1
  - role: worker
    labels:
      custom-name: worker-2